---
name: depup
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: 14 14 * * *  # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]
  workflow_dispatch:
permissions: {}
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-depup/with-pr@94a1aaf4e4923064019214b48a43276218af7ad5  # v1.6.4
        with:
          file: Dockerfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog
          labels: bump:minor
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-depup/with-pr@94a1aaf4e4923064019214b48a43276218af7ad5  # v1.6.4
        with:
          file: Dockerfile
          version_name: RUFF_VERSION
          repo: astral-sh/ruff
          labels: bump:minor
