---
name: Docker Image CI
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date
          +%s)
